format_version: 2
environments:
  ci:
    pipelines:
      - "cinemas-ui"
      - "cinemas-api"
pipelines:
  "cinemas-ui":
    group: movies
    materials:
      cinemas-ui:
        git: "git@git.thoughtworks.net:bootcamp-trainers/just-cinemas-ui.git"
    stages:
      - build:
          jobs:
            build:
              tasks:
                - script: |
                    echo "it works"
  "cinemas-api":
    group: movies
    materials:
      cinemas-backend:
        git: "git@git.thoughtworks.net:bootcamp-trainers/just-cinemas-services.git"
    stages:
      - build:
          jobs:
            build:
              tasks:
                - script: |
                    echo "it works"
