format_version: 2
environments:
  ci:
    pipelines:
      - "cinemas-ui"
      - "cinemas-api"
pipelines:
  "cinemas-ui":
    group: just-cinemas
    materials:
      cinemas-ui:
        git: "git@git.thoughtworks.net:bootcamp-trainers/just-cinemas-ui.git"
    stages:
      - lint:
          jobs:
            lint:
              resources:
                - node
              tasks:
                - script: |
                    npm install
                    npm run lint
      - test:
          jobs:
            test:
              resources:
                - node
              tasks:
                - script: |
                    npm install
                    npm run test
      - build:
          jobs:
            build:
              artifacts:
                - build:
                    source: dist
                    destination: dist
              tabs:
                dist: dist
              resources:
                - node
              tasks:
                - script: |
                    npm install
                    npm run dist
  "cinemas-api":
    group: just-cinemas
    materials:
      cinemas-backend:
        git: "git@git.thoughtworks.net:bootcamp-trainers/just-cinemas-services.git"
    stages:
      - build:
          jobs:
            build:
              tasks:
                - script: |
                    echo "it works"
