format_version: 2
pipelines:
  "cinemas-ui":
    group: just-cinemas
    materials:
      cinemas-ui:
        git: "https://github.com/Sethuraman/just-cinemas-ui.git"
    stages:
     - test:
          jobs:
            test:
              resources:
                - node
              tasks:
                - script: |
                    npm install yarn -g
                    /opt/node-*-linux-x64/bin/yarn install
                    ln -s /opt/node-*-linux-x64/bin/yarn /bin/yarn
                    CI=true TEST_REPORT_PATH=reports/test yarn test --coverage
     - build:
          jobs:
            build:
              resources:
                - node
              tasks:
                - script: |
                    /opt/node-*-linux-x64/bin/yarn build
                    cp -R build/* /static-assets/*
                    touch /static-assets/restart.txt
