format_version: 2
pipelines:
  "cinemas-api":
    group: just-cinemas
    materials:
      cinemas-backend:
        git: "https://github.com/tak2siva/SpiCinemas.git"
    stages:
      - test:
          jobs:
            test:
              resources:
                - java
              artifacts:
                - test:
                    source: build/reports/tests/**
                    destination: test-reports/
              tabs:
                Report: test-reports/build/reports/tests/test/index.html
              tasks:
                - script: |
                    mv src/main/resources/application-ci.yml src/main/resources/application-test.yml
                    ./gradlew clean test -Penv=ci
      - build:
          jobs:
            build:
              artifacts:
                - build:
                    source: build/libs/*.jar
                    destination: libs/
              resources:
                - java
              tasks:
                - script: |
                    ./gradlew clean assemble -Penv=ci
                    cp build/libs/*.jar /artifacts/.
                    touch /artifacts/restart.txt
