format_version: 2
pipelines:
  "cinemas-api":
    group: just-cinemas
    materials:
      cinemas-backend:
        git: "git@git.thoughtworks.net:bootcamp-trainers/just-cinemas-services.git"
    stages:
      - test:
          jobs:
            test:
              resources:
                - java
              tasks:
                - script: |
                    cp src/test/resources/test-application.properties.ci src/test/resources/test-application.properties
                    ./gradlew clean test
      - build:
          jobs:
            build:
              resources:
                - java
              tasks:
                - script: |
                    cp src/test/resources/test-application.properties.ci src/test/resources/test-application.properties
                    ./gradlew clean test
