format_version: 2
pipelines:
  "cinemas-ui":
    group: just-cinemas
    materials:
      cinemas-ui:
        git: "https://github.com/Sethuraman/just-cinemas-ui.git"
    stages:
     - test:
          jobs:
            test:
              resources:
                - node
              tasks:
                - script: |
                    yarn install
                    CI=true TEST_REPORT_PATH=reports/test yarn test --coverage
     - build:
          jobs:
            build:
              resources:
                - node
              tasks:
                - script: |
                    yarn build
                    cp -R build/* /static-assets/*
